# Generated by Django 3.2.25 on 2024-07-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmePipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.FloatField()),
                ('nps', models.FloatField()),
                ('sch', models.FloatField()),
                ('od', models.FloatField()),
                ('wt', models.FloatField()),
                ('mass', models.FloatField()),
            ],
        ),
    ]
