# Generated by Django 3.2.25 on 2024-07-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_flangerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flangerating',
            old_name='max_p',
            new_name='max_pressure',
        ),
        migrations.AlterField(
            model_name='flangerating',
            name='flange_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flangerating',
            name='material',
            field=models.CharField(max_length=20),
        ),
    ]
