# Generated by Django 3.2.25 on 2024-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20240727_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flangerating',
            name='max_pressure',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flangerating',
            name='temp_range',
            field=models.CharField(max_length=200),
        ),
    ]
